version: '3.8'

services:
  # ONLYOFFICE Document Server
  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-docs
    restart: always
    ports:
      - "8080:80"
    environment:
      - JWT_SECRET=tu_secreto_jwt_muy_seguro_2024
      - JWT_ENABLED=true
      - JWT_HEADER=Authorization
      - WOPI_ENABLED=true
      # Configuración de memoria (ajustar según recursos)
      - NODE_OPTIONS=--max-old-space-size=2048
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice
      - onlyoffice_fonts:/usr/share/fonts/truetype/custom
    networks:
      - onlyoffice_network

  # Nginx Proxy Reverso (opcional para SSL)
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - onlyoffice
    networks:
      - onlyoffice_network

  # Redis para cache (recomendado para mejor rendimiento)
  redis:
    image: redis:alpine
    container_name: onlyoffice-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - onlyoffice_network

  # PostgreSQL para metadatos (opcional)
  postgres:
    image: postgres:13
    container_name: onlyoffice-db
    restart: always
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_PASSWORD=password_seguro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - onlyoffice_network

volumes:
  onlyoffice_data:
  onlyoffice_log:
  onlyoffice_fonts:
  redis_data:
  postgres_data:

networks:
  onlyoffice_network:
    driver: bridge
