# Render deployment configuration

# Backend Service
services:
  - type: web
    name: sistema-aclaraciones-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend Static Site  
  - type: web
    name: sistema-aclaraciones-frontend
    env: static
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: dashboard/dist
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: max-age=31536000
      - source: /index.html
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /aclaraciones
        destination: /index.html
      - type: rewrite
        source: /ventas
        destination: /index.html
      - type: rewrite
        source: /caja
        destination: /index.html
      - type: rewrite
        source: /cargos-auto
        destination: /index.html
      - type: rewrite
        source: /panel
        destination: /index.html
      - type: rewrite
        source: /recuperacion
        destination: /index.html
      - type: rewrite
        source: /dashboard-*
        destination: /index.html
      - type: rewrite
        source: /validador-telefonos
        destination: /index.html
      - type: rewrite
        source: /vendedoras-status
        destination: /index.html
      - type: rewrite
        source: /sucursal-bloque
        destination: /index.html
      - type: rewrite
        source: /sucursales-alerta
        destination: /index.html
      - type: rewrite
        source: /ingresar-aclaraciones
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://sistema-aclaraciones-backend.onrender.com
