services:
  # Backend API Server
  - type: web
    name: buscadores-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend Static Site
  - type: static
    name: buscadores-spa
    buildCommand: |
      cd dashboard
      npm ci
      npm run build
    staticPublishPath: dashboard/dist
    routes:
      - type: rewrite
        source: "/**"
        destination: "/index.html"
